% This file lists the descriptions of the datasets and codes we used in
% this project 


%% Descriptions of the Datasets under the folder Linear_open_system
%  The file named 'LOS_beta001_alpha05.mat' stores a dataset generated by
%  the linear open system with one source of induced variation (50% decrease of
%  A(6,7), i.e., alpha=0.5) and with individual variation at level
%  beta=0.01.

%  The file named 'LOS_beta04_alpha05_degenerate.mat' stores a dataset generated by
%  the linear open system with one source of induced variation (50% decrease of
%  A(6,7), i.e., alpha=0.5) and with individual variation at level
%  beta=0.4. This setting is an example to show that CP model with two cmponents
%  is degenerate.

%  The file named 'LOS_diff_inflowoutflow.mat' stores a dataset generated by
%  the linear open system with the levels of the inflow and outflow at
%  gamma1=0.005 and gamma2=0.01, with one source of induced variation (50% decrease of
%  A(6,7), i.e., alpha=0.5), and with individual variation at level beta=0.65. 
%  This setting is an example to show that degeneracy disappears when the level of 
%  the inflow and outflow is low.

%  The file named 'LOS_diff_A.mat' stores a dataset generated by
%  the linear open system with matrix A whose subdiagnal elements is replaced by 
%  a scaled random vector on $ [0,4]$, e.g.,  
%  $ [3.13,1.30,2.29,2.50,1.35,4.00,2.86,2.43,1.42,0.78,0.89]* 10^3 $,
%  with one source of induced variation (50% decrease of
%  A(6,7),i.e.,alpha=0.5), and with individual variation at level beta=0.65.
%  This example is to show that degeneracy disappears when different
%  kinetic constants are considered.



%% Descriptions of the Datasets under the folder glycolysis_model
%  The file named 'GLM_beta002_PFKalpha05.mat' stores a dataset generated by
%  the glycolysis model with one source of induced variation (50% decrease of
%  VmaxPFK, i.e., alpha=0.5) and with individual variation at level beta=0.02.

%  The file named 'GLM_beta036_PFKalpha05.mat' stores a dataset generated by
%  the glycolysis model with one source of induced variation (50% decrease of
%  VmaxPFK, i.e., alpha=0.5) and with individual variation at level beta=0.36.
%  This setting is an example showing that  CP model is more preperable for
%  data with higher individual variation

%  The file named 'GLM_beta05_PFKalpha05.mat' stores a dataset generated by
%  the glycolysis model with one source of induced variation (50% decrease of
%  VmaxPFK, i.e., alpha=0.5) and with individual variation at level beta=0.5.


%  The file named 'GLM_beta05_alpha05_100sample.mat' stores a dataset generated by
%  the glycolysis model with 100 subjects, with one source of induced variation (50% decrease of
%  VmaxPFK, i.e., alpha=0.5) and with individual variation at level beta=0.5.


%  The file named 'GLM_beta002_PFKalpha05_PYKalpha05.mat' stores a dataset generated by
%  the glycolysis model with two sources of induced variation (50% decrease of
%  VmaxPFK, alpha=0.5, and 50% decrease of VmaxPYK, alpha=0.5) and with individual 
%  variation at level beta=0.02.




%% Descriptions of the Datasets under the folder cholesterol_model
%  The file named 'CLM_beta002_mutant1.mat' stores a dataset generated by
%  the glycolysis model with one source of induced variation (mutant1, i.e., alpha=0.62)
%  and with individual variation at level beta=0.02.


%  The file named 'CLM_beta065_mutant1.mat' stores a dataset generated by
%  the cholesterol model with one source of induced variation (mutant1, i.e., alpha=0.62)
%  and with individual variation at level beta=0.65.
%  This setting is an example showing that  CP model is more preperable for
%  data with higher individual variation.


%  The file named 'CLM_beta002_mutant6_mutant10.mat' stores a dataset generated by
%  the cholesterol model with two sources of induced variation (mutant6, alpha=0.35, and 
%  mutant10, alpha=0.95) and with individual variation at level beta=0.02.



%% Descriptions of the codes under the folder Code_CP_Paralind
%  The file named 'CP_example.m' is an example code for moddling the data
%  with CP model using the tensor toolbox with multiple initialisations.
%  For running the code, please first install the tensor Toolbox.

%  The file named 'paralind_example.m' is an example code for moddling the data
%  with Paralind model with multiple initialisations.
%  To run the code, 'paralind_Lu_ortho.m' is needed.

%  The file named 'paralind_Lu_ortho.m' is the code for computing the
%  factorization of the Paralind model. The open source for this code can
%  be found on http://www.models.life.ku.dk/paralind, but there is no
%  orthogonality constraint in the open source and the authors have added the orthogonal
%  constraint, see in 'paralind_Lu_ortho.m'.

%  The file named 'CP_missing_example.m' is an example code for computing
%  the Tensor Completion Score (TCS) using CP model in the cross-validation.
%  To run the code, tensor toolbox is needed.

%  The file named 'paralind_missing_example.m' is an example code for computing
%  the Tensor Completion Score using Paralind model in the
%  cross-validation.
%  To run the code, the PLS toolbox is needed.

%  The file named 'TC.m' is for computing the Tucker congruency


