% This file lists the descriptions of the datasets and the codes we used in
% this project 


%% Descriptions of the Datasets under the folder Linear_open_system
%  The file named 'LOS_beta001_alpha05.mat' stores the dataset generated by
%  the linear open system with one source of induced variation (50% decrease of
%  A(7,6), i.e., alpha=0.5) and with individual variation at level
%  beta=0.01.

%  The file named 'LOS_beta03_alpha05.mat' stores the dataset generated by
%  the  linear open system with one source of induced variation (50% decrease of
%  A(7,6), i.e., alpha=0.5) and with individual variation at level
%  beta=0.3.

%  The file named 'Diff_A_LOS_beta001_alpha05.mat' stores the dataset generated by
%  the linear open system with b=10^3*[0.5,0,0,0,0,0,0,0,0,0,0]^T and matrix A  a 
%  tridiagonal matrix for which the diagonal elements are set to be 
%  10^3*[-1, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2] and the superdiagonal and 
%  subdiagonal elements are set to be 10^3*[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
%  with one source of induced variation (50% decrease of A(7,6), i.e., alpha=0.5) 
%  and with individual variation at level beta=0.01.



%% Descriptions of the Datasets under the folder glycolysis_model
%  The file named 'GLM_beta002_PFKalpha05.mat' stores the dataset generated by
%  the glycolysis model with one source of induced variation (50% decrease of
%  VmaxPFK, i.e., alpha=0.5), and with individual variation at level beta=0.02.

%  The file named 'GLM_beta036_PFKalpha05.mat' stores the dataset generated by
%  the glycolysis model with one source of induced variation (50% decrease of
%  VmaxPFK, i.e., alpha=0.5), and with individual variation at level beta=0.36.


%  The file named 'GLM_beta05_PFKalpha05.mat' stores the dataset generated by
%  the glycolysis model with one source of induced variation (50% decrease of
%  VmaxPFK, i.e., alpha=0.5), and with individual variation at level beta=0.5.


%  The file named 'GLM_beta05_alpha05_100sample.mat' stores the dataset generated by
%  the glycolysis model with 100 subjects, with one source of induced variation (50% decrease of
%  VmaxPFK, i.e., alpha=0.5), and with individual variation at level beta=0.5.


%  The file named 'GLM_beta002_PFKalpha05_PYKalpha05.mat' stores the dataset generated by
%  the glycolysis model with two sources of induced variation (50% decrease of
%  VmaxPFK, alpha=0.5, and 50% decrease of VmaxPYK, alpha=0.5) and with individual 
%  variation at level beta=0.02.




%% Descriptions of the Datasets under the folder cholesterol_model
%  The file named 'CLM_beta002_mutant1.mat' stores the dataset generated by
%  the cholesterol model with one source of induced variation (mutant1, i.e., alpha=0.62)
%  and with individual variation at level beta=0.02.


%  The file named 'CLM_beta065_mutant1.mat' stores the dataset generated by
%  the cholesterol model with one source of induced variation (mutant1, i.e., alpha=0.62)
%  and with individual variation at level beta=0.65.



%  The file named 'CLM_beta002_mutant6_mutant10.mat' stores the dataset generated by
%  the cholesterol model with two sources of induced variation (mutant6, alpha=0.35, and 
%  mutant10, alpha=0.95), and with individual variation at level beta=0.02.



%% Descriptions of the codes under the folder Code_CP_Paralind
%  The file named 'paralind_Lu_ortho.m' is the code for computing the
%  factorization of the Paralind model. The open source for this code can
%  be found on http://www.models.life.ku.dk/paralind, but there is no
%  orthogonality constraint in the open source and there are several bugs in the code. 
%  The authors have added the orthogonal constraint and fixed the bugs; see in 'paralind_Lu_ortho.m'. 

%  The file named 'TC.m' is for computing the Tucker congruency

%  The file named 'CP_example.m' is an example code for moddling the data
%  with CP model using the tensor toolbox with multiple initialisations.
%  To run the code, tensor toolbox as well as
%  the L-BFGS-B implementation from
%  https://github.com/stephenbeckr/L-BFGS-B-C is needed

%  The file named 'paralind_example.m' is an example code for moddling the data
%  with Paralind model with multiple initialisations.
%  To run the code, 'paralind_Lu_ortho.m' is needed.
  

%  The file named 'CP_missing_example.m' is an example code for computing
%  the Tensor Completion Score (TCS) using CP model in the cross-validation.
%  To run the code, tensor toolbox is needed and
%  the L-BFGS-B implementation from
%  https://github.com/stephenbeckr/L-BFGS-B-C is needed

%  The file named 'paralind_missing_example.m' is an example code for computing
%  the Tensor Completion Score using Paralind model in the
%  cross-validation.
%  To run the code, paralind_Lu_ortho.m is needed.

%  The file named 'create_missing_data_pattern.m' creates a randomly missing element indicator tensor.
%  This functon is from the CMTF_Toolbox.






