clear all
clc
close all
% The plot is taking the data generated by the glycolysis model with one
% source of induced variation  as an example
%% load data % The preprocessed data and labels are stored in the data set Y
load('Y.mat','Y')
X=tensor(Y.data);
labelss = Y.label{2};
s=size(X);
%% plot the preprocessed data
figure
for i=1:s(2)
    subplot(4,3,i)
    for j=1:s(1)
        if j<=10
            plot(1:1:20,squeeze(X.data(j,i,:)),'r')
            xlim([1 20]);
            hold on
        elseif j<=20
            plot(1:1:20,squeeze(X.data(j,i,:)),'b')
            xlim([1 20]);
            hold on
        end
    end
    title(labelss(i,:))
end
%% Paralind model
nb_starts =60;
H0=[1 1];
A0=[];B0=[];C0=[];
Options(1)=1e-10;
Options(2)=10000;
Options(3)=2;
R=1;S=2;
Constraints = [0 -1 3 1];
for i=1:nb_starts
    [A,H,B,C,fit,it,explainvar]=paralind_Lu_ortho(X.data,R,S,Constraints,Options,H0,A0,B0,C0);
    FactorsXL{i}{1}=A*H;
    FactorsXL{i}{2}=B;
    FactorsXL{i}{3}=C;
    Fac_X{i}=ktensor(FactorsXL{i});
    erF(i)=norm(X-full(Fac_X{i}));
    expvar(i)=explainvar;
end
%% uniqueness test
Fit_round = round(erF,8);
best_F_index = find(Fit_round == min(Fit_round));
eps = .05; %Arbtitraly picked, ideas for a values are appreciated
if length(best_F_index)==1
    unique_test = 2;
    disp('Need more random starts to determine uniqueness')
    worst_check = 0;
elseif length(best_F_index) > 1
    check_matrix = zeros(length(best_F_index));
    for i = 1:length(best_F_index)
        for j = 1:length(best_F_index)
            check_matrix(i,j) = score(Fac_X{best_F_index(j)},Fac_X{best_F_index(i)},'lambda_penalty',false);
        end
    end
    worst_check = min(min(check_matrix));
    if worst_check < (1-eps) %Checks to see if factors are the same if F is
        unique_test = 0;
    else
        unique_test = 1;
    end
end


%%
unique=unique_test
[er,best_F_index]=sort(erF,'ascend');
Fac=Fac_X{best_F_index(1)};
fit=expvar(best_F_index(1))
Fac=Fac_X{best_F_index(1)};
a1=Fac.U{1}(:,1);a2=Fac.U{1}(:,2);
b1=Fac.U{2}(:,1);b2=Fac.U{2}(:,2);
c1=Fac.U{3}(:,1);c2=Fac.U{3}(:,2);
Fac.lambda(1)=norm(a1)*norm(b1)*norm(c1);
Fac.lambda(2)=norm(a2)*norm(b2)*norm(c2);
Fac.U{1}(:,1)=a1/norm(a1);Fac.U{1}(:,2)=a2/norm(a2);
Fac.U{2}(:,1)=b2/norm(b2);Fac.U{2}(:,2)=b1/norm(b1);
Fac.U{3}(:,1)=c2/norm(c2);Fac.U{3}(:,2)=c1/norm(c1);
%% plot
nm_comp=2;
Z1=labelss;
Z2={'subjects','metabolites','time'};
Z3{1}=1:20;Z3{2}=[1:11];Z3{3}=1:20;
labels{1} = {'C1','C2','C3','C4','C5','C6','C7','C8','C9','C10',...
    'C11','C12','C13','C14','C15','C16','C17','C18','C19','C20'};
labels{2} = {'1','2','3','4','5','6','7','8','9','10','11'};
labels{3} = {'T1','T2','T3','T4','T5','T6','T7','T8','T9','T10',...
    'T11','T12','T13','T14','T15','T16','T17','T18','T19','T20'};
Leglab = {'Comp1', 'Comp2'};
Leglab3 = {'Comp1', 'Comp2','comp3'};
%% plot CP 2
Fac.U{1}(:,1)=-Fac.U{1}(:,1);Fac.U{1}(:,2)=-Fac.U{1}(:,2);
Fac.U{2}(:,1)=-Fac.U{2}(:,1);Fac.U{2}(:,2)=-Fac.U{2}(:,2);
figure
for i=1:3
    subplot(3,1,i)
    if i==1
        for j=1:nm_comp
            plot(Z3{i},Fac.U{i}(:,j),'-o','LineWidth',2.4)
            hold on
            legend(Leglab,'TextColor','blue')
        end
        
    elseif i==2
        for j=1:nm_comp
            plot(Z3{i},Fac.U{i}(:,j),'-o','LineWidth',2.4)
            set(gca,'xtick',Z3{i},'xticklabel',Z1)
            hold on
            legend(Leglab,'TextColor','blue')
            ax = gca;
            ax.YGrid = 'on';
            ax.GridAlpha = 1;
            title(Z2{i})
        end
    else
        for j=1:nm_comp
            plot(Z3{i},Fac.U{i}(:,j),'-o','LineWidth',2.4)
            hold on
            legend(Leglab,'TextColor','blue')
        end
    end
    set(gca,'FontSize', 18)
    title(Z2{i})
end




